version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "🔍 Current directory:"
      - pwd
      - echo "📂 Listing root directory:"
      - ls -al
      - echo "📦 Installing backend dependencies..."
      - cd app-tier
      - npm install
      - cd ../web-tier
      - echo "📦 Installing frontend dependencies..."
      - npm install

  build:
    commands:
      - echo "⚙️ Building frontend..."
      - cd web-tier
      - npm run build
      - cd ..

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - app-tier/**/*
    - web-tier/build/**/*
    - nginx.conf
