version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "🔍 Current working directory:"
      - pwd

      - echo "📂 Root directory listing:"
      - ls -al

      - echo "📂 Full folder tree:"
      - find . -type d

      - echo "📦 Installing frontend dependencies..."
      - test -d application-code/web-tier && cd application-code/web-tier || test -d web-tier && cd web-tier || (echo '❌ web-tier folder not found' && exit 1)
      - npm install

      - echo "📦 Installing backend dependencies..."
      - test -d ../backend-tier && cd ../backend-tier || test -d ../../application-code/backend-tier && cd ../../application-code/backend-tier || test -d backend-tier && cd backend-tier || (echo '❌ backend-tier folder not found' && exit 1)
      - npm install

  build:
    commands:
      - echo "⚙️ Building frontend..."
      - test -d ../web-tier && cd ../web-tier || test -d ../../application-code/web-tier && cd ../../application-code/web-tier || test -d web-tier && cd web-tier || (echo '❌ web-tier folder not found for build' && exit 1)
      - npm run build
      - echo "✅ Build complete."

artifacts:
  files:
    - appspec.yml
    - scripts/*
    - application-code/web-tier/build/**/*
    - application-code/backend-tier/**/*
