version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing frontend dependencies...
      - cd web-tier
      - npm install
      - cd ../backend-tier
      - echo Installing backend dependencies...
      - npm install

  build:
    commands:
      - echo Building frontend...
      - cd ../web-tier
      - npm run build
      - echo Build complete.

artifacts:
  files:
    - appspec.yml
    - scripts/*
    - web-tier/build/**/* 
    - backend-tier/**/*
