version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Listing root directory:"
      - ls -al
      - echo "Installing frontend dependencies..."
      - cd application-code/web-tier
      - npm install
      - echo "Installing backend dependencies..."
      - cd ../backend-tier
      - npm install

  build:
    commands:
      - echo "Building frontend..."
      - cd ../web-tier
      - npm run build
      - echo "Build complete."

artifacts:
  files:
    - appspec.yml
    - scripts/*
    - application-code/web-tier/build/**/* 
    - application-code/backend-tier/**/*
